### ISSUE TITLE
Error code required for failure to input headings correctly

### ISSUE THREAD

**Issue by JAdderley** [FinnOD/mappings#2]
Currently if a column name is input incorrectly, the error returned states the columnNameDict instead of what was input by the user.

Need an error code which states the column name that is what is requested by the User.

Might also be good to add a line stating 'wrong column name used, please check spelling on columns and capitalisation.'

**Comment by FinnOD** [comment]
Hi Jack,

Could you please also check that this works, and you're happy with the error message. If you're not you can reopen this issue.
