### ISSUE TITLE
Need error code and termination: Failure to make progress on trails

### ISSUE THREAD

**Issue by JAdderley** [FinnOD/mappings#3]
If the dataset doesn't network well together or too high of a minimum trail length is set, then the trails will not accumulate. 

Need to terminate a trail if it doesn't begin to accumulate after 2 minutes - is this possible?
- Then throw an error suggestion to reduce minimumTrailLength otherwise not enough data is available.

**Comment by FinnOD** [comment]
Do we want it to be if the trails don't accumulate at all? Or just if they're not accumulating fast enough? Either way it is possible to implement.

**Comment by JAdderley** [comment]
Mainly trying to address no accumulation at all. - Fast enough is a little hard to define, and may be network size dependent

**Comment by FinnOD** [comment]
Hi Jack, Could you please test this and let me know if you like the error message?
